version: '3.7'
volumes:
  pgdb:

services:
  app:
    image: node:bullseye
    volumes:
      - './:/app'
    environment:
      - DB_NAME=main
      - DB_PASSWORD=password
      - DB_USER_NAME=main
      - DB_HOST=db
      - SMTP_PORT=1025
      - SMTP_HOST=mailhog
      - MAILER_LOGIN=
      - MAILER_PASS=
      - MAILER_SENDER_EMAIL=test@local
    entrypoint: ''
    working_dir: /app
    command: bash -c "npm i && npm run start:migrate && npm run start:dev"
    ports:
      - "8080:8080"
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    ports:
      - 5432:5432
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui